"""Feature engineering for household lapse (decision D2), on the real seed only.

Why this module reads the seed and not gold
-------------------------------------------
Gold's fact table is **100% `is_synthetic = true`** — every row came from the amplifier. That is
correct: the amplified stream exists to exercise the *pipeline* (small files, late arrival, drift,
duplicate delivery), and it did.

But requirement MLR-003 forbids synthetic rows in evaluation, and ADR-0003 explains why in a
sentence worth repeating: a model trained on data generated by a rule you wrote will recover the
rule you wrote, then report that as accuracy. The amplifier resamples whole observed baskets, so
it does not invent a generating rule — but it also cannot produce a household whose behaviour the
seed never showed. Every household in the stream is a resampled copy of a real one, so a
train/test split over amplified data leaks by construction: the same real basket can land on both
sides.

So the ML layer reads `transaction_data` directly. 2,595,732 real lines, 2,500 real households.
The pipeline work and the modelling work use different inputs on purpose, and saying so is the
difference between a portfolio that demonstrates ML and one that demonstrates ML theatre.

The temporal split, and the leakage it prevents
-----------------------------------------------
`DAY` is a relative integer 1..711 with no calendar anchor (ADR-0003, and `data/README.md`). That
rules out seasonality features but does not rule out a clean temporal split, which is what matters
here:

    DAY   1 .. 547   observation window — every feature is computed from this alone
    DAY 548 .. 711   outcome window     — the label is whether the household transacted here

The split is on *time*, never on households. A random household split would let a household's
early baskets train the model that predicts its later ones — a leak that inflates every metric and
is invisible in a confusion matrix.

Nothing after day 547 may touch a feature. `assert_no_leakage` enforces that rather than trusting
the reader, because leakage is the ML defect that most reliably survives review: the code looks
fine, the metrics look good, and the model fails in production for reasons nobody can reconstruct.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

# The observation/outcome boundary. 547 of 711 days is ~77% for features, leaving ~23 weeks to
# observe the outcome — long enough that "did not return" means lapsed rather than "was between
# shopping trips". A grocery household's inter-purchase interval is days, not months.
SPLIT_DAY = 547
MAX_DAY = 711


@dataclass(frozen=True)
class FeatureSet:
    X: pd.DataFrame
    y: pd.Series
    household_key: pd.Series
    feature_names: list[str]

    def __len__(self) -> int:
        return len(self.X)

    @property
    def lapse_rate(self) -> float:
        return float(self.y.mean())


def build(transactions: pd.DataFrame, *, split_day: int = SPLIT_DAY) -> FeatureSet:
    """Build lapse features from raw seed transactions.

    `transactions` is the dunnhumby `transaction_data` table with its original column names.
    """
    tx = transactions.rename(columns=str.upper)
    observed = tx[tx["DAY"] <= split_day]
    outcome = tx[tx["DAY"] > split_day]

    if observed.empty:
        raise ValueError(f"No transactions on or before day {split_day}.")

    returned = set(outcome["HOUSEHOLD_KEY"].unique())

    basket = observed.groupby(["HOUSEHOLD_KEY", "BASKET_ID"]).agg(
        basket_amt=("SALES_VALUE", "sum"),
        basket_lines=("PRODUCT_ID", "count"),
        basket_day=("DAY", "first"),
        basket_store=("STORE_ID", "first"),
    )

    per_household = basket.groupby("HOUSEHOLD_KEY").agg(
        frequency_baskets=("basket_amt", "size"),
        monetary_amt=("basket_amt", "sum"),
        avg_basket_amt=("basket_amt", "mean"),
        std_basket_amt=("basket_amt", "std"),
        avg_basket_lines=("basket_lines", "mean"),
        last_day=("basket_day", "max"),
        first_day=("basket_day", "min"),
        distinct_stores=("basket_store", "nunique"),
    )

    line_level = observed.groupby("HOUSEHOLD_KEY").agg(
        distinct_products=("PRODUCT_ID", "nunique"),
        total_units=("QUANTITY", "sum"),
        retail_disc_amt=("RETAIL_DISC", "sum"),
        coupon_disc_amt=("COUPON_DISC", "sum"),
    )

    features = per_household.join(line_level)

    # Recency is measured from the split boundary, not from wall-clock time. Anchoring to today
    # would make every household look lapsed by however long ago the data was collected.
    features["recency_days"] = split_day - features["last_day"]
    features["tenure_days"] = features["last_day"] - features["first_day"]

    # Inter-purchase rhythm. A household that shops weekly and has been silent for three weeks is
    # a different risk from one that shops quarterly and has been silent for three weeks, and
    # recency alone cannot tell them apart — which is precisely where the baseline should lose.
    features["avg_days_between"] = np.where(
        features["frequency_baskets"] > 1,
        features["tenure_days"] / (features["frequency_baskets"] - 1),
        np.nan,
    )
    features["recency_over_cadence"] = features["recency_days"] / features["avg_days_between"]

    features["discount_share"] = features["retail_disc_amt"].abs() / features[
        "monetary_amt"
    ].replace(0, np.nan)
    features["coupon_share"] = features["coupon_disc_amt"].abs() / features["monetary_amt"].replace(
        0, np.nan
    )

    # Trend: spend in the final eight weeks against the household's own average. A household
    # already slowing down is the one an intervention can still reach.
    recent_window = observed[observed["DAY"] > split_day - 56]
    recent = recent_window.groupby("HOUSEHOLD_KEY")["SALES_VALUE"].sum().rename("recent_amt")
    features = features.join(recent)
    features["recent_amt"] = features["recent_amt"].fillna(0.0)
    weeks_observed = (features["tenure_days"] / 7).clip(lower=1)
    features["recent_vs_typical"] = features["recent_amt"] / (
        features["monetary_amt"] / weeks_observed * 8
    ).replace(0, np.nan)

    features = features.drop(columns=["last_day", "first_day"])
    label = (~features.index.isin(returned)).astype(int)

    feature_names = list(features.columns)
    return FeatureSet(
        X=features.reset_index(drop=True),
        y=pd.Series(label, name="lapsed"),
        household_key=pd.Series(features.index, name="household_key"),
        feature_names=feature_names,
    )


def assert_no_leakage(transactions: pd.DataFrame, *, split_day: int = SPLIT_DAY) -> None:
    """MLR-006. Fail loudly if any feature could see past the split boundary.

    The check is deliberately crude and structural: rebuild features from a truncated input and
    assert they are byte-identical. If any feature read the outcome window, truncating it changes
    the result. A subtler check would be easier to fool, and this one cannot be satisfied by
    accident.
    """
    full = build(transactions, split_day=split_day)
    truncated = build(transactions[transactions["DAY"] <= split_day], split_day=split_day)

    if not full.X.equals(truncated.X):
        differing = [c for c in full.feature_names if not full.X[c].equals(truncated.X[c])]
        raise AssertionError(
            f"Leakage: {differing} changed when the outcome window was removed. "
            "A feature is reading data from after the split boundary."
        )
