#!/usr/bin/env python3
"""Profile the dunnhumby seed and emit docs/architecture/dataset-profile.md.

Why a script and not a notebook: the profile is an input to architecture decisions (clustering
keys, skew mitigation, feature availability). Numbers that inform a decision must be regenerable
on demand, or the decision cannot be re-examined when the data changes.

Deliberately stdlib-only — no pandas, no Spark. This runs before any environment exists, which is
the point: you should be able to look at the data before you have decided how to process it.

    python3 scripts/profile_seed.py [--dataset complete-journey] [--stdout]
"""

from __future__ import annotations

import argparse
import csv
import sys
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
RAW = REPO_ROOT / "data" / "raw"
OUT = REPO_ROOT / "docs" / "architecture" / "dataset-profile.md"

# Percentiles of the *key* population at which to report cumulative row share.
# A skew curve is far more informative than a single "max/median" number: it tells you whether
# you have one hot key (salt it) or a heavy head (partition strategy problem).
SKEW_POINTS = (0.01, 0.05, 0.10, 0.25, 0.50)


@dataclass
class TableProfile:
    name: str
    path: Path
    rows: int = 0
    columns: list[str] = field(default_factory=list)
    bytes_: int = 0
    blank_counts: Counter[str] = field(default_factory=Counter)
    distinct: dict[str, int] = field(default_factory=dict)
    numeric_range: dict[str, tuple[float, float]] = field(default_factory=dict)


def _iter_csv(path: Path):
    with path.open(newline="", encoding="utf-8-sig") as handle:
        yield from csv.DictReader(handle)


def profile_table(
    path: Path, *, track_distinct: tuple[str, ...], track_range: tuple[str, ...]
) -> TableProfile:
    prof = TableProfile(name=path.stem, path=path, bytes_=path.stat().st_size)
    seen: dict[str, set[str]] = {c: set() for c in track_distinct}
    ranges: dict[str, list[float]] = {}

    with path.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        prof.columns = list(reader.fieldnames or [])
        for row in reader:
            prof.rows += 1
            for col, value in row.items():
                if value is None or value.strip() == "":
                    prof.blank_counts[col] += 1
            for col in track_distinct:
                if row.get(col):
                    seen[col].add(row[col])
            for col in track_range:
                raw = row.get(col)
                if not raw:
                    continue
                try:
                    val = float(raw)
                except ValueError:
                    continue
                bounds = ranges.setdefault(col, [val, val])
                bounds[0] = min(bounds[0], val)
                bounds[1] = max(bounds[1], val)

    prof.distinct = {c: len(v) for c, v in seen.items()}
    prof.numeric_range = {c: (v[0], v[1]) for c, v in ranges.items()}
    return prof


def skew_curve(counts: Counter[str]) -> list[tuple[float, int, float]]:
    """Return (key_share, key_count, cumulative_row_share) at each SKEW_POINT."""
    ordered = sorted(counts.values(), reverse=True)
    total = sum(ordered)
    n = len(ordered)
    out: list[tuple[float, int, float]] = []
    for point in SKEW_POINTS:
        take = max(1, round(n * point))
        out.append((point, take, sum(ordered[:take]) / total))
    return out


def key_frequency(path: Path, column: str) -> Counter[str]:
    counts: Counter[str] = Counter()
    for row in _iter_csv(path):
        counts[row[column]] += 1
    return counts


def build_report(root: Path) -> str:
    csv_dir = next(p for p in root.rglob("*.csv")).parent
    files = sorted(csv_dir.glob("*.csv"))

    lines: list[str] = []
    add = lines.append

    add("# Seed dataset profile — dunnhumby, The Complete Journey")
    add("")
    add("> Generated by `scripts/profile_seed.py`. Do not edit by hand; regenerate.")
    add("> These measurements are inputs to ADR-0003 and ADR-0007. If they change, revisit both.")
    add("")

    add("## Table inventory")
    add("")
    add("| Table | Rows | Size | Columns |")
    add("|---|---:|---:|---|")

    profiles: dict[str, TableProfile] = {}
    spec = {
        "transaction_data": (
            ("household_key", "STORE_ID", "PRODUCT_ID", "BASKET_ID"),
            ("DAY", "WEEK_NO", "SALES_VALUE", "QUANTITY"),
        ),
        "product": (("PRODUCT_ID", "DEPARTMENT", "COMMODITY_DESC", "MANUFACTURER", "BRAND"), ()),
        "hh_demographic": (("household_key",), ()),
        "causal_data": (("PRODUCT_ID", "STORE_ID"), ("WEEK_NO",)),
        "coupon": (("COUPON_UPC", "PRODUCT_ID", "CAMPAIGN"), ()),
        "coupon_redempt": (("household_key", "COUPON_UPC"), ("DAY",)),
        "campaign_table": (("household_key", "CAMPAIGN"), ()),
        "campaign_desc": (("CAMPAIGN",), ("START_DAY", "END_DAY")),
    }

    for path in files:
        track_distinct, track_range = spec.get(path.stem, ((), ()))
        print(f"  profiling {path.name} ...", file=sys.stderr)
        prof = profile_table(path, track_distinct=track_distinct, track_range=track_range)
        profiles[path.stem] = prof
        add(f"| `{prof.name}` | {prof.rows:,} | {prof.bytes_ / 1e6:.1f} MB | {len(prof.columns)} |")

    add("")
    add("## Cardinalities")
    add("")
    add("| Table | Column | Distinct |")
    add("|---|---|---:|")
    for prof in profiles.values():
        for col, count in sorted(prof.distinct.items()):
            add(f"| `{prof.name}` | `{col}` | {count:,} |")

    add("")
    add("## Value ranges")
    add("")
    add("| Table | Column | Min | Max |")
    add("|---|---|---:|---:|")
    for prof in profiles.values():
        for col, (lo, hi) in sorted(prof.numeric_range.items()):
            add(f"| `{prof.name}` | `{col}` | {lo:,.2f} | {hi:,.2f} |")

    # ---- Skew, the headline finding -------------------------------------------------
    tx = csv_dir / "transaction_data.csv"
    add("")
    add("## Key skew — measured, not assumed")
    add("")
    add("This is the single most consequential measurement in the profile. It determines whether")
    add("skew handling is a demonstration or a requirement.")
    add("")
    for column, label in (
        ("STORE_ID", "store"),
        ("household_key", "household"),
        ("PRODUCT_ID", "product"),
    ):
        print(f"  skew: {column} ...", file=sys.stderr)
        counts = key_frequency(tx, column)
        ordered = sorted(counts.values(), reverse=True)
        median = ordered[len(ordered) // 2]
        add(f"### `{column}` ({len(counts):,} distinct {label}s)")
        add("")
        add("| Top share of keys | Keys | Share of transaction lines |")
        add("|---:|---:|---:|")
        for point, take, share in skew_curve(counts):
            add(f"| {point:.0%} | {take:,} | **{share:.1%}** |")
        add("")
        add(f"Max / median lines per {label}: **{ordered[0] / median:,.0f}×**")
        add("")

    # ---- Coverage gaps ---------------------------------------------------------------
    hh_tx = profiles["transaction_data"].distinct["household_key"]
    hh_demo = profiles["hh_demographic"].rows
    add("## Coverage gaps")
    add("")
    add(f"- Households appearing in transactions: **{hh_tx:,}**")
    add(
        f"- Households with demographic attributes: **{hh_demo:,}** "
        f"(**{hh_demo / hh_tx:.0%}** coverage)"
    )
    add("")
    add("This gap is a modelling constraint, not a data-loading bug. Any feature set that assumes")
    add("demographics will silently train on a biased third of the population. Behavioural")
    add("features must carry the model; demographics can only ever be an optional enrichment.")
    add("")

    # ---- Blanks -----------------------------------------------------------------------
    add("## Blank / empty values")
    add("")
    any_blanks = False
    add("| Table | Column | Blank rows | Share |")
    add("|---|---|---:|---:|")
    for prof in profiles.values():
        for col, count in sorted(prof.blank_counts.items(), key=lambda kv: -kv[1]):
            if count:
                any_blanks = True
                add(f"| `{prof.name}` | `{col}` | {count:,} | {count / prof.rows:.2%} |")
    if not any_blanks:
        add("| — | — | 0 | 0% |")
        add("")
        add("No blanks. This is itself notable: it means the seed will not exercise null-handling")
        add("rules on its own, so those quality rules must be validated against injected cases")
        add("rather than assumed covered.")
    add("")

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset", default="complete-journey")
    parser.add_argument("--stdout", action="store_true", help="print instead of writing the doc")
    args = parser.parse_args()

    root = RAW / args.dataset
    if not root.exists():
        print(
            f"Dataset not found at {root.relative_to(REPO_ROOT)}. "
            "Run: python3 scripts/fetch_data.py",
            file=sys.stderr,
        )
        return 1

    report = build_report(root)
    if args.stdout:
        print(report)
    else:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(report, encoding="utf-8")
        print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
